all:
  hosts:
    demo:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/jguichard/projets/DocSnap/ansible/demo/.vagrant/machines/default/virtualbox/private_key

  vars:
    ansible_python_interpreter: /usr/bin/python3